#!/usr/bin/env bash

ln -s `pwd`/.vim ~/.vim
ln -s `pwd`/bin ~/bin
ln -s `pwd`/.gitconfig ~/.gitconfig
ln -s `pwd`/.tmux.conf ~/.tmux.conf
ln -s `pwd`/.vimrc ~/.vimrc
ln -s `pwd`/.zshrc ~/.zshrc
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
